apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  volumeMode: Filesystem
  awsElasticBlockStore:
    volumeID: vol-012439aa856003590
    fsType: ext4
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: ebs-pvc
