# apiVersion: v1
# kind: ServiceAccount
# metadata:
#    name: admin
#    namespace: default

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#    name: admin-role
# rules:
#    - apiGroups: ["*"]
#      resources: ["*"]
#      verbs: ["*"]
# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: admin-rolebinding
# subjects:
#   - kind: ServiceAccount
#     name: admin
#     apiGroup: rbac.authorization.k8s.io
# roleRef:
#     kind: ClusterRole
#     name: admin-role
#     apiGroup: rbac.authorization.k8s.io
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-rolebinding
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
